name = "personality-spark"
compatibility_date = "2025-01-19"
main = "src/index.js"

# Zone-based routing for custom domain
[[routes]]
pattern = "www.personalityspark.com/*"
zone_name = "personalityspark.com"

# Static assets configuration
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"
run_worker_first = ["/api/*"]

# Environment variables
[env.production]
vars = { ENVIRONMENT = "production" }